// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWSg1bERKOakSh3XO9IsKvtuewDI4ojg',
    appId: '1:162591583298:android:3a7a36483911d3477e91db',
    messagingSenderId: '162591583298',
    projectId: 'silap-7c845',
    databaseURL: 'https://silap-7c845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silap-7c845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyuK6I17a4DLmW_94oSVcoB2Kp5UadfI',
    appId: '1:162591583298:ios:4024cd9f2e99459c7e91db',
    messagingSenderId: '162591583298',
    projectId: 'silap-7c845',
    databaseURL: 'https://silap-7c845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'silap-7c845.firebasestorage.app',
    iosBundleId: 'com.crimson.silap.praja.silap',
  );

}